### PR TITLE
Allows an easy first configuration via .env

### PR DESCRIPTION
**Pull request by dwulfde**
I think that this could be helpful for fast using this great plugin.

### CODE REVIEW

**Comment by dwulfde** [comment]
mh... any ideas? :(

**Comment by timgws** [comment]
`env()` is not supported in Laravel 4.

**Comment by dwulfde** [comment]
oh - okay. Then this merge would be a bad idea :)

**Comment by timgws** [comment]
Also, the index name was changed from `my_custom_index_name` to `default`, which would have broken some unit tests :)

**Pull request closed without merging**
