### PR TITLE
Load eager relations and pivot recursive

### PR DESCRIPTION
**Pull request by chuangbo**
Implement of #54 and #46.

### CODE REVIEW

**Comment by timgws** [comment]
Thanks :+1:

**Comment by chuangbo** [comment]
Thank for prompt merging.

Actually this needs tests as I've just tested in my cases which is very limited.

**Comment by timgws** [comment]
All of this code needs proper tests, not just this that I have merged.

I have some (admittedly simple) CLI tests that deletes and index, indexes some new data and does a few different searches. This passed these tests, so I have accepted the PR.

I am going to write up some proper mocked unit tests in the next couple of days/weeks which will allow us to have a better idea if all the code is actually working correctly.

If you want to go ahead and start working on this, go ahead. To be honest, I don't have the time _just yet_ :)

**Comment by chuangbo** [comment]
Do you have any plan on how we going to mock? I noticed elasticsearch-php use mockery and Elastica use docker.

Should we open a discussion issue for mocking test?

**Comment by timgws** [comment]
Opening a discussion issue seems like the best way to go forward.

My idea would be to use Mockery and a handful of different hosted Elasticsearch providers, basically, going through each of the providers, deleting an index, creating a new one, inserting ~ 20 or so documents, and attempting all the common `Collection` methods on a returned result.

**Pull request merged**
